sunny0826/kubecm

- .github/workflows/go.yaml
- .github/workflows/release.yaml
- .gitignore
- Makefile
- cmd/alias.go
- docs/en-us/cli/kubecm_alias.md
- docs/zh-cn/cli/kubecm_alias.md
- hack/docgen/gen.go
- Optimizing alias  subcommands
- fix action config
> Update Alias Cmd

- cmd/merge.go
- cmd/switch.go
- cmd/switch_test.go
- Reference #18 
- add unit test
> feature of #18

- .github/workflows/go.yaml
- go.mod
> update go version

- cmd/cloud.go
- cmd/cloud_test.go
- go.mod
- go.sum
- pkg/cloud/aliyun.go
- pkg/cloud/cloud.go
- pkg/cloud/tencent.go
> cmd cloud support: add kubeconfig of tencent to local

- .github/workflows/codeql-analysis.yml
- .github/workflows/go.yaml
> update action config

- cmd/merge.go
> check merge file type

- cmd/merge.go
- cmd/merge_test.go
> add unit test

- cmd/cloud.go
- cmd/create.go
- cmd/namespace.go
- cmd/root.go
- cmd/utils.go
Hi, is just made the menu size configurable
> feat: make size of menus configurable

- cmd/merge.go
useful when building docker image
> feat: add centos-like -y assumeyes flag for merge command

- .github/workflows/go.yaml
> fix: update action on

- cmd/add.go
Support read config from stdin.
```sh
sudo cat /etc/kubernetes/admin.conf |  kubecm add -f -
```
> support read config from stdin

- docs/en-us/cli/kubecm_add_cloud.md
- docs/zh-cn/cli/kubecm_add_cloud.md
> docs(add cloud): add provider Rancher docs

- .github/workflows/e2e-test.yaml
- Makefile
> add e2e test

- .github/workflows/e2e-test.yaml
- .gitignore
- cmd/merge.go
> feat: merge cmd support for multi file input

- Makefile
- cmd/root.go
- docs/en-us/README.md
- docs/en-us/cli/kubecm.md
- docs/en-us/cli/kubecm_add.md
- docs/en-us/cli/kubecm_add_cloud.md
- docs/en-us/cli/kubecm_alias.md
- docs/en-us/cli/kubecm_clear.md
- docs/en-us/cli/kubecm_completion.md
- docs/en-us/cli/kubecm_create.md
- docs/en-us/cli/kubecm_delete.md
- docs/en-us/cli/kubecm_list.md
- docs/en-us/cli/kubecm_merge.md
- docs/en-us/cli/kubecm_namespace.md
- docs/en-us/cli/kubecm_rename.md
- docs/en-us/cli/kubecm_switch.md
- docs/en-us/cli/kubecm_version.md
- docs/zh-cn/README.md
- docs/zh-cn/cli/kubecm.md
- docs/zh-cn/cli/kubecm_merge.md
- hack/docgen/gen.go
> docs: update docs

- .github/workflows/e2e-test.yaml
- .goreleaser.yml
- README.md
- cmd/completion.go
- docs/README.md
- docs/en-us/cli/kubecm_completion.md
- docs/zh-cn/cli/kubecm_completion.md
> Docs: fix completion

- .github/workflows/e2e-test.yaml
- .goreleaser.yml
- Makefile
- cmd/version.go
- go.mod
- go.sum
- main.go
- pkg/update/update.go
- pkg/update/update_test.go
- version/version.go
> feat: add new release check

- README.md
- cmd/add.go
- cmd/cloud.go
- cmd/cloud_list.go
- docs/README.md
- docs/en-us/README.md
- docs/en-us/cli/kubecm.md
- docs/en-us/cli/kubecm_cloud.md
- docs/en-us/cli/kubecm_cloud_add.md
- docs/en-us/cli/kubecm_cloud_list.md
- docs/zh-cn/README.md
- docs/zh-cn/cli/kubecm_cloud.md
- docs/zh-cn/cli/kubecm_cloud_add.md
- docs/zh-cn/cli/kubecm_cloud_list.md
Update doc help info, to make it better to use.
> Update doc help info

- cmd/root.go
- cmd/utils.go
> refactor: add mac-notify flag to set mac notification banners to disabled by default

- docs/en-us/introduction.md
- docs/zh-cn/introduction.md
> docs: fix broken link

- cmd/utils.go
> feat: Change the context name character limit

- cmd/namespace.go
- cmd/namespace_test.go
- cmd/utils.go
- go.mod
> test: add unit test for namespace.go

- cmd/list.go
- cmd/utils.go
- cmd/utils_test.go
- go.mod
- go.sum
> test: add unit test for MoreInfo

- .github/workflows/e2e-test.yaml
- .github/workflows/go.yaml
- .github/workflows/release.yaml
- Makefile
- cmd/add.go
- cmd/alias.go
- cmd/alias_test.go
- cmd/clear_test.go
- cmd/merge.go
- cmd/merge_test.go
- cmd/root.go
- cmd/utils_test.go
- go.mod
- main.go
- pkg/update/update.go
> ci: update go version

- .github/workflows/e2e-test.yaml
- .github/workflows/go.yaml
- .github/workflows/release.yaml
- go.mod
> refactor: 💡 update go version to 1.20

- .github/workflows/release.yaml
> ci: 🎡 update release action

- .github/workflows/codeql-analysis.yml
> ci: 🎡 fix  codeql action

- .all-contributorsrc
- .github/workflows/codeql-analysis.yml
- README.md
- cmd/namespace.go
- docs/en-us/contribute.md
- docs/zh-cn/contribute.md
Verify the length of current contexts in kubeconfig to be > 0 before using current context in the namespace command.
Fixes #850
> Verify the length of contexts in namespace cmd

- docs/en-us/install.md
- docs/zh-cn/install.md
> docs: ✏️ fix install docs

- README.md
> README add new badges

- .github/workflows/release.yaml
- .goreleaser.yml
> update goreleaser config

- .github/workflows/go.yaml
- .golangci.yml
- cmd/add_test.go
- cmd/cloud.go
- cmd/namespace.go
- cmd/utils.go
- go.mod
> update go version to 1.24.2

- cmd/delete_range_test.go
> fix unit test
