- cmd/add.go
- cmd/clear.go
- cmd/clear_test.go
- cmd/cmd.go
- cmd/list.go
- cmd/list_test.go
- cmd/root.go
- cmd/switch.go
- cmd/utils.go
- cmd/utils_test.go
- docs/en-us/README.md
- docs/en-us/_sidebar.md
- docs/en-us/cli/kubecm_clear.md
- docs/en-us/cli/kubecm_ls.md
- docs/zh-cn/README.md
- docs/zh-cn/_sidebar.md
- docs/zh-cn/cli/kubecm_clear.md
- docs/zh-cn/cli/kubecm_ls.md
- docs/zh-cn/cli/kubecm_switch.md
- go.mod
- go.sum
- add `clear` cmd
- add filter future to `ls` cmd #11 
- add utest
- fix #15 
- update docs
- some optimisation
> some new future

- go.mod
- go.sum
This PR will fix the issue the align issue when context name is Chinese
This issue is related to bndr/gotabulate#11 which is fixed in master branch, but there is no tag yet.
The fixed result is below
> Fix `kubecm ls` alignment when the context name is Chinese

- cmd/add.go
> select first context when there is only one

- docs/_sidebar.md
- docs/en-us/_sidebar.md
- docs/zh-cn/_sidebar.md
Fix website 404 link url at: https://kubecm.cloud/en-us/cli/kubecm_add_cloud
> Fix website cloud link 404

- .krew.yaml
- README.md
- docs/README.md
- docs/en-us/README.md
- docs/en-us/install.md
- docs/zh-cn/README.md
- docs/zh-cn/install.md
Hi sunny0826,
This is an awesome tool! Thanks for your open source contribution :)
It helps us to manage kubeconfig more efficiently.
I submitted a PR https://github.com/kubernetes-sigs/krew-index/pull/2545 to add this tool to krew.
To make this tool to broader users.
> Add to kubectl plugin kc

- .krew.yaml
- Makefile
- README.md
- docs/en-us/README.md
- docs/zh-cn/README.md
To make it consistent with the krew-index: https://github.com/kubernetes-sigs/krew-index/blob/master/plugins/kc.yaml
> Fix krew yaml && typo

- main.go
When auth provider with name oidc is used, kubecm will throw an error: no Auth Provider found for name "oidc". This commit fixes the issue.
> Fix: add oidc auth method

- .github/workflows/e2e-test.yaml
- cmd/add.go
added >= to  if len(kc.config.Contexts) >= 1, as it could be a user has just 1 context in current file
> context can be 1 or bigger

- cmd/cmd.go
- cmd/export.go
- cmd/export_test.go
- docs/_sidebar.md
- docs/en-us/_sidebar.md
- docs/en-us/cli/kubecm_export.md
- docs/zh-cn/_sidebar.md
- docs/zh-cn/cli/kubecm_export.md
Add **export** command to enable users to export specified contexts from kubeconfig file.
```bash
kubecm export cluster-1  cluster-2 -f /tmp/export-config.yaml 
Context Export:「cluster-1」
Context Export:「cluster-2」
```
> Add kubecm export command

- cmd/cloud.go
- cmd/cloud_add.go
- codecov.yml
- go.mod
- go.sum
- pkg/cloud/aws.go
- pkg/cloud/aws_test.go
> feat: cloud add aws eks

- .goreleaser.yml
- https://github.com/sunny0826/kubecm/issues/720
```console
$ goreleaser --version
____       ____      _
/ ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
\____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com
GitVersion:    1.19.1
GitCommit:     6b46a1a6aa51e45bd281d55b6e5a2315ee82f643
GitTreeState:  false
BuildDate:     2023-06-29T12:55:30Z
BuiltBy:       goreleaser
GoVersion:     go1.20.5
Compiler:      gc
ModuleSum:     h1:MVAFo62jkj6/JflxruefIwfFTqNTeNtkT12Hab1o2Lk=
Platform:      darwin/arm64
```
```console
$ goreleaser release --clean --snapshot
• starting release...
• loading config file …
```
> chore: fix asset names

- cmd/switch.go
Before I realized there was an existing alias of `s` for the `kubecm switch` command, I setup a function in my shell profile to create one called `sw` (I also shorten kubecm to kc):
```shell
function kc() {
if [[ $@ == "sw" ]]; then
command kubecm switch
else
command kubecm "$@"
fi
}
```
This PR adds `sw` as a native alias in addition to `s`. My muscle memory prevents me from using `kubecm s` instead 😆
> feat: Added an additional alias to the switch command

- cmd/root.go
- cmd/utils.go
- docs/en-us/cli/kubecm.md
- docs/en-us/cli/kubecm_add.md
- docs/en-us/cli/kubecm_alias.md
- docs/en-us/cli/kubecm_clear.md
- docs/en-us/cli/kubecm_cloud.md
- docs/en-us/cli/kubecm_cloud_add.md
- docs/en-us/cli/kubecm_cloud_list.md
- docs/en-us/cli/kubecm_completion.md
- docs/en-us/cli/kubecm_create.md
- docs/en-us/cli/kubecm_delete.md
- docs/en-us/cli/kubecm_export.md
- docs/en-us/cli/kubecm_list.md
- docs/en-us/cli/kubecm_merge.md
- docs/en-us/cli/kubecm_namespace.md
- docs/en-us/cli/kubecm_rename.md
- docs/en-us/cli/kubecm_switch.md
- docs/en-us/cli/kubecm_version.md
Not always one would want to print the whole table of all contexts after each successful write.
Especially if `kubecm switch` or `kubecm ns` are often used.
This PR adds the option to silence it.
[x] Added the flag
[x] Tested locally
[x] Ran `make doc-gen`
> feat: Allow silencing context table print upon config write

- cmd/completion.go
- docs/en-us/cli/kubecm_completion.md
- docs/zh-cn/cli/kubecm_completion.md
- hack/kubectl-plugin-completion/kubectl_complete-kc.sh
Close #786.
- Added a new hack script to proxy arguments to Cobra's `_completion` command
- Translated documentation for Simplified Chinese
- Refined the original documentations for English
- Refined the help message of `completion` sub command, for better reading experience and instructions
- Added instructions about how to configure and setup the completions for `kubectl kc`
`completion --help` now prints:
```
❯ ./main completion --help
To load completions for kubecm cli:
For Bash users:
source <(kubecm completion bash)
kubecm completion bash > /etc/bash_completion.d/kubecm
kubecm completion bash > /usr/local/etc/bash_completion.d/kubecm
For Zsh users, execute:
echo "autoload -U compinit; compinit" >> ~/.zshrc
kubecm completion zsh > "${fpath[1]}/_kubecm"
For fish users, execute:
kubecm …
```
> docs: added documentations and help message for setup completions when used as kubectl plugin

- cmd/root.go
Now we can use  `-u` instead of `--ui-size`
> Add shorthand letter for `--ui-size`

- cmd/delete.go
- cmd/delete_test.go
I added a check to make sure that we don't delete a user or a cluster that is in use by another context than the one getting deleted.
I also added a unit test that deletes a context that references a user that is referenced within another context.
- Fixes #814
> Fix `delete` removes user even if another context is using it

- .all-contributorsrc
- README.md
- docs/en-us/contribute.md
- docs/zh-cn/contribute.md
> docs: ✏️ add contribute docs

- .github/workflows/e2e-test.yaml
- .github/workflows/go.yaml
- .github/workflows/release.yaml
- go.mod
- go.sum
bump to use go1.21 for build
relates to https://github.com/Homebrew/homebrew-core/pull/159379
> feat: bump to use go1.21

- .golangci.yml
```
WARN [runner] The linter 'varcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter. Replaced by unused.
```
followup #847
> chore: remove `varcheck` check

- .github/workflows/e2e-test.yaml
- cmd/root.go
- cmd/utils.go
get export env KUBECONFIG
resolves #850
> feat: 🎸 get export env KUBECONFIG

- .github/workflows/e2e-test.yaml
- .gitignore
- cmd/create.go
- cmd/create_test.go
- docs/en-us/cli/kubecm_create.md
> feat: 🎸 rewrite create commands

- docs/404.html
- docs/index.html
GitHub Pages wasn't playing nicely with the website's routing
> Fix routing on website

- cmd/add.go
- cmd/add_test.go
- cmd/cloud_add.go
- cmd/merge.go
- docs/en-us/cli/kubecm_add.md
- docs/en-us/cli/kubecm_merge.md
- docs/zh-cn/cli/kubecm_add.md
- docs/zh-cn/cli/kubecm_merge.md
Add the `--select-context` parameter allowing the user to choose which context should be added when running the `kubecm add` and `kubecm merge` commands.
Prepare two kubeconfig.
```bash
./kubecm list --config kubeconfig1
+------------+-------------+-------------+----------+-------------------------+--------------+
|   CURRENT  |     NAME    |   CLUSTER   |   USER   |          SERVER         |   Namespace  |
+============+=============+=============+==========+=========================+==============+
|      *     |   context1  |   cluster1  |   user1  |   https://example1.com  |    default   |
+------------+-------------+-------------+----------+-------------------------+--------------+
./kubecm list --config kubeconfig2
+------------+-------------+-------------+----------+---------------- …
```
> feat: allow select context for kubecm add and merge command

- cmd/add.go
- cmd/add_test.go
- cmd/cloud_add.go
- cmd/merge.go
- docs/en-us/cli/kubecm_add.md
- docs/en-us/cli/kubecm_merge.md
- docs/zh-cn/cli/kubecm_add.md
- docs/zh-cn/cli/kubecm_merge.md
- go.mod
Implement: https://github.com/sunny0826/kubecm/pull/952#discussion_r1606253799
Add a new parameter `--context` to specify the context to be added when running kubecm add or merge command.
Prepare two kubeconfig.
```bash
./kubecm list --config kubeconfig1
+------------+-------------+-------------+----------+-------------------------+--------------+
|   CURRENT  |     NAME    |   CLUSTER   |   USER   |          SERVER         |   Namespace  |
+============+=============+=============+==========+=========================+==============+
|      *     |   context1  |   cluster1  |   user1  |   https://example1.com  |    default   |
+------------+-------------+-------------+----------+-------------------------+--------------+
./kubecm list --config kubeconfig2 …
```
> feat: allow specify the context to be added

- cmd/add.go
- cmd/merge.go
- cmd/root.go
- cmd/utils.go
- cmd/utils_test.go
> fixing issue #888

- cmd/list.go
- cmd/utils.go
resolves https://github.com/sunny0826/kubecm/issues/972
> add KUBECM_DISABLE_K8S_MORE_INFO env to disable output moreinfo

- cmd/delete.go
- cmd/export.go
- cmd/rename.go
- cmd/switch.go
- cmd/utils.go
It was annoying to have a different order for the context every time I ran `kubecm switch`
> Sort contexts before listing them

- cmd/add.go
- cmd/add_test.go
- cmd/cloud_add.go
Add --insecure-skip-tls-verify when executing `kubecm add`
https://github.com/sunny0826/kubecm/issues/1041
> [Feature] Add --insecure-skip-tls-verify when executing kubecm add

- cmd/add.go
- cmd/add_test.go
See issue #1047 and Files changed.
resolves #1047
> fix: cluster and user name conflict on add kubeconfig with same context cluster and user

- cmd/utils.go
I need to switch k8s contexts frequently at work, using `kubecm switch`, which works well, but doesn't support fuzzy searches, and I need to remember exactly what each context name is when there are too many contexts, so I'm submitting this pr.
It should be noted that my `kubecm` is modified, and I'll show you an example of fuzzy search.
Before:
After:
> feat: add fuzzy search

- cmd/root.go
- cmd/utils.go
> display more items and enter fullscreen
